### ISSUE TITLE
Problem with new "send after failure" trigger 

### ISSUE THREAD

**Issue by BenCoullNeveu** [FlyingKiwis/Nina.DiscordAlert#5]
Hello, just reporting that when I used the new trigger, it would automatically end my sequence. Not sure why this happened, but when I removed the trigger the sequence ran normally.
Just thought I should let you know!

**Comment by FlyingKiwis** [comment]
Hi, could you please upload your nina log file from when it crashed?

**Comment by FlyingKiwis** [comment]
Recently fixed the alert trigger in 1.1.3, if you are still having issues after 1.1.3 please reopen
